// <auto-generated />
namespace Piranhas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SwimmertoUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SwimmertoUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201504240441562_Swimmer to User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
